<?php

namespace Database\Seeders;

use App\Models\Escenario;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EscenariosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $escenarios = [
            ['id' => 1, 'cod_escenario' => 1, 'id_frases' => 1, 'escenario' => 'Afiliado al ISR Régimen Sobre las Utilidades de Actividades Lucrativas.', 'efecto' => 'No', 'nombre' => 'Sujeto a pagos trimestrales ISR', 'tipo_dte' => 'NA', 'frase_automatica' => 'SI'],
            ['id' => 2, 'cod_escenario' => 2, 'id_frases' => 1, 'escenario' => 'Afiliado al ISR Régimen Opcional Simplificado Sobre Ingresos de Actividades Lucrativas (y NO cuenta con una Resolución de la SAT que le permitiría hacer el pago directo y le evitaría ser objeto de retención)', 'efecto' => 'Sí', 'nombre' => 'Sujeto a retención definitiva ISR', 'tipo_dte' => 'NA', 'frase_automatica' => 'SI'],
            ['id' => 3, 'cod_escenario' => 3, 'id_frases' => 1, 'escenario' => 'Afiliado al ISR Régimen Opcional Simplificado Sobre Ingresos de Actividades Lucrativas (y SÍ cuenta con una Resolución de la SAT que le permite hacer el pago directo y le evita ser objeto de retención)', 'efecto' => 'No', 'nombre' => 'Sujeto a pago directo ISR ( XXXX - dd/mm/aaaa).  *Donde XXXX es el número de resolución de la afiliación especial del contribuyente emisor y dd/mm/aaaa la fecha de de dicha resolución.', 'tipo_dte' => 'NA', 'frase_automatica' => 'SI'],
            ['id' => 4, 'cod_escenario' => 1, 'id_frases' => 2, 'escenario' => 'Es Agente de Retención del IVA', 'efecto' => 'SI', 'nombre' => 'Agente de Retención del IVA', 'tipo_dte' => 'NA', 'frase_automatica' => 'NA'],
            ['id' => 6, 'cod_escenario' => 1, 'id_frases' => 3, 'escenario' => 'El contribuyente está afiliado al IVA,  en cualquiera de estos regimenes:  • Pequeño contribuyente • Contribuyente Agropeguario • Pequeño contribuyente Régimen Electrónico • Contribuyente Agropecuario Régimen Electrónico Especia', 'efecto' => 'NA', 'nombre' => 'No genera derecho a crédito fiscal', 'tipo_dte' => 'NA', 'frase_automatica' => 'SI'],
            ['id' => 7, 'cod_escenario' => 1, 'id_frases' => 4, 'escenario' => 'Exportaciones. Cuando el vendedor exporya bienes o servicios', 'efecto' => 'NA', 'nombre' => 'Exenta del IVA (art. 7 num. 2 Ley del IVA)', 'tipo_dte' => 'FACT, FCAM', 'frase_automatica' => 'NA'],
            ['id' => 8, 'cod_escenario' => 2, 'id_frases' => 4, 'escenario' => 'Servicios que presten las instituciones fiscalizadas por la Superintendencia de Bancos y las bolsas de valores autorizadas para operar en el país.', 'efecto' => 'NA', 'nombre' => 'Exenta del IVA (art. 7 num. 4 Ley del IVA)', 'tipo_dte' => 'FACT. FCAM', 'frase_automatica' => 'NA'],
            ['id' => 9, 'cod_escenario' => 3, 'id_frases' => 4, 'escenario' => 'Ventas de cooperativas. Cuando una cooperativa le vende bienes o servicios a sus asociados, cooperativas, federaciones, centrales de servicios y confederaciones de cooperativas.', 'efecto' => 'NA', 'nombre' => 'Exenta del IVA (art. 7 num. 5 Ley del IVA)', 'tipo_dte' => 'FACT, FCAM', 'frase_automatica' => 'NA'],
            ['id' => 10, 'cod_escenario' => 4, 'id_frases' => 4, 'escenario' => 'Donaciones. A asociaciones, fundaciones e instituciones, educativas, culturales de asistencia o de servicio social y las religiosas no lucrativas.', 'efecto' => 'NA', 'nombre' => 'Exenta del IVA (art.  7 num. 9 Ley del IVA)', 'tipo_dte' => 'RDON', 'frase_automatica' => 'NA'],
            ['id' => 11, 'cod_escenario' => 5, 'id_frases' => 4, 'escenario' => 'Pagos por el derecho de ser miembro y las cuotas periódicas a las asociaciones o instituciones sociales, gremiales, culturales,científicas, educativas y deportivas, así como a los colegios de profesionales y los partidos políticos.', 'efecto' => 'NA', 'nombre' => 'Exenta del IVA (art. 7 num. 10 Ley del IVA)', 'tipo_dte' => 'RECI', 'frase_automatica' => 'NA'],
            ['id' => 12, 'cod_escenario' => 6, 'id_frases' => 4, 'escenario' => 'Servicios exentos que prestan las asociaciones, fundaciones e instituciones educativas, de asistencia o de servicio social y las religiosas, y otras no lucrativas.', 'efecto' => 'NA', 'nombre' => 'Exenta del IVA (art. 7 num. 13 Ley del IVA', 'tipo_dte' => 'FACT, FCAM, RECI', 'frase_automatica' => 'NA'],
            ['id' => 13, 'cod_escenario' => 7, 'id_frases' => 4, 'escenario' => 'Venta de activos de Bancos o Sociedades Financieras a las que la Superintendencia de Bancos haya aprobado un plan de regulación o en que exista Junta de Exclusión de activos y pasivos, cuando se transfieran a otros Bancos o sociedades financieras, previa autorización de la Junta Monetaria. Esta exención tendrá validez siempre que la operación no sea para eludir responsabilidades civiles, penales, o de otra naturaleza.', 'efecto' => 'NA', 'nombre' => 'Exenta del IVA (art. 7 num. 14 Ley del IVA)', 'tipo_dte' => 'FACT, FCAM', 'frase_automatica' => 'NA'],
            ['id' => 14, 'cod_escenario' => 8, 'id_frases' => 4, 'escenario' => 'Servicios exentos centros educativos privados en lo que respecta a la matrícula de inscripción, colegiaturas y derechos de examen, de los cursos que tengan autorizados por la autoridad competente.', 'efecto' => 'NA', 'nombre' => 'Exenta del IVA (art. 8 num. 1 Ley del IVA)', 'tipo_dte' => 'RECI', 'frase_automatica' => 'NA'],
            ['id' => 15, 'cod_escenario' => 9, 'id_frases' => 4, 'escenario' => 'Medicamentos. Cuando una compañía farmacéutica le vende medicamentos genéricos o antirretrovirales a determinados pacientes.', 'efecto' => 'NA', 'nombre' => 'Exenta del IVA (art. 7 num. 15 Ley del IVA)', 'tipo_dte' => 'FACT, FCAM', 'frase_automatica' => 'NA'],
            ['id' => 16, 'cod_escenario' => 10, 'id_frases' => 4, 'escenario' => 'Vehículos: Cuando se vende un vehículo terrestre del modelo de dos o más años anteriores al del año en curso.', 'efecto' => 'NA', 'nombre' => 'Esta factura no incluye IVA (art. 55 Ley del IVA)', 'tipo_dte' => 'FACT, FCAM', 'frase_automatica' => 'NA'],
            ['id' => 17, 'cod_escenario' => 11, 'id_frases' => 4, 'escenario' => 'Ventas maquilas. Cuando el vendedor vende bienes o servicios de producción local a empresas calificadas bajo el decreto 29-89. Base legal: artículo 12 bis literal g del decreto 29-89 Ley de Maquila; artículo 11 del Acuerdo Gubernativo 5-2013 Reglamento de la Ley del IVA. Operaciones específicas de maquilas, usuarios de zonas francas y coexportadores. Para los casos de ventas no afectas al IVA que pueden darse entre estos actores. Base legal: artículo 36 bis y 36 ter del Decreto 29-89, Ley de Fomento a la Actividad Exportadora y de Maquila', 'efecto' => 'NA', 'nombre' => 'No afecta al IVA (Decreto 29-89 Ley de Maquila)', 'tipo_dte' => 'FACT, FCAM', 'frase_automatica' => 'NA'],
            ['id' => 18, 'cod_escenario' => 12, 'id_frases' => 4, 'escenario' => 'Ventas zonas francas. Ventas a zonas francas. Cuando el vendedor vende bienes o servicios de producción local a empresas calificadas bajo el decreto 65-89. Base legal: artículo 22 bis literal e del decreto 29-89 Ley de Zonas Francas Ventas de zonas francas. Por transferencias de mercancías que se realicen dentro y entre zonas francas. Base legal: artículo 22 literal c del Decreto 65-89 Ley de Zonas Francas.', 'efecto' => 'NA', 'nombre' => 'No afecta al IVA (Decreto 65-89 Ley de Zonas Francas)', 'tipo_dte' => 'FACT, FCAM', 'frase_automatica' => 'NA'],
            ['id' => 19, 'cod_escenario' => 13, 'id_frases' => 4, 'escenario' => 'Venta de vivienda: Cuando la vivienda no exceda los límites de medición y valor que contempla la ley del Impuesto al Valor Agregado; así como las segundas y subsiguientes transferencias de dominio de viviendas por cualquier título, que tributen conforme la Ley del Impuesto de Timbres Fiscales.', 'efecto' => 'NA', 'nombre' => 'Exenta del IVA (art. 7 num. 12,  Ley del IVA)', 'tipo_dte' => 'FACT, FCAM', 'frase_automatica' => 'NA'],
            ['id' => 20, 'cod_escenario' => 14, 'id_frases' => 4, 'escenario' => 'Venta de títulos y acciones: La creación, emisión, circulación y transferencia de títulos de crédito, títulos valores y acciones de cualquier clase, exceptuando la factura cambiaria, cuando la emisión, aceptación o negociación corresponda a actos gravados por la presente ley', 'efecto' => 'NA', 'nombre' => 'Exenta del IVA (art. 7 num. 6 Ley del IVA)', 'tipo_dte' => 'FACT, FCAM', 'frase_automatica' => 'NA'],
            ['id' => 21, 'cod_escenario' => 15, 'id_frases' => 4, 'escenario' => 'Venta al menudeo en mercados. La venta al menudeo de carnes, pescado, mariscos, frutas y verduras frescas, cereales. legumbres y granos básicos a consumidores finales en mercados cantonales y municipales, siempre que tales ventas no excedan de cien quetzales (Q. 100.00) por cada transacción.', 'efecto' => 'NA', 'nombre' => 'Exenta del IVA (art. 7 num. 11 Ley del IVA)', 'tipo_dte' => 'FACT, FCAM', 'frase_automatica' => 'NA'],
            ['id' => 22, 'cod_escenario' => 16, 'id_frases' => 4, 'escenario' => 'Ventas y servicios universidades. Las universidades autorizadas para funcionar en el país', 'efecto' => 'NA', 'nombre' => 'Exenta del IVA (art. 8 num. 2 Ley del IVA)', 'tipo_dte' => 'FACT, FCAM, RECI', 'frase_automatica' => 'NA'],
            ['id' => 23, 'cod_escenario' => 17, 'id_frases' => 4, 'escenario' => 'Ventas Usuarios Zolic. Los usuarios que se instalen y operen dentro de la Zona Libre gozarán de exención al Impuesto al Valor Agregado por los hechos y actos gravados realizados dentro de la Zona Libre', 'efecto' => 'NA', 'nombre' => 'Exenta del IVA (art. 32 literal c, Ley Orgánica Zolic)', 'tipo_dte' => 'FACT, FCAM', 'frase_automatica' => 'NA'],
            ['id' => 24, 'cod_escenario' => 18, 'id_frases' => 4, 'escenario' => 'Ventas exentas del IVA por disposición específica. Cuando se efectúe una venta que corresponde a una operación exenta, o una venta a contribuyentes que cuenten con disposiciones específicas de exención al IVA.', 'efecto' => 'NA', 'nombre' => '(Contribuyentes con disposiciones específicas de exención al IVA)', 'tipo_dte' => 'FACT, FCAM', 'frase_automatica' => 'NA'],
            ['id' => 25, 'cod_escenario' => 19, 'id_frases' => 4, 'escenario' => 'Faltante de inventario de bienes perecederos, casos fortuitos, de fuerza mayor o delitos. Cuando se facture faltante de inventario que no corresponden al hecho generador del IVA, es decir cuando ocurra por bienes perecederos, casos fortuitos, de fuerza mayor o delitos contra el patrimonio.', 'efecto' => 'NA', 'nombre' => 'Exenta del IVA (art. 3 num. 7 Ley del IVA)', 'tipo_dte' => 'FACT, FCAM', 'frase_automatica' => 'NA'],
            ['id' => 26, 'cod_escenario' => 20, 'id_frases' => 4, 'escenario' => 'Aportes sociedades de emprendimiento.  Cuando una persona individual o jurídica realice aportes a las sociedades de emprendimiento', 'efecto' => 'NA', 'nombre' => 'Aportes (art. 35 Ley de Fortalecimiento al Emprendimiento)', 'tipo_dte' => 'RECI', 'frase_automatica' => 'NA'],
            ['id' => 27, 'cod_escenario' => 21, 'id_frases' => 4, 'escenario' => 'Otros cargos, impuestos y/o tasas a otros países, no sujetos a IVA. Cuando se incluyan en el boleto aéreo cargos, o impuestos y/o tasas para otros países, no sujetos a IVA.', 'efecto' => 'NA', 'nombre' => 'Cargos e impuestos no sujetos a IVA (Aerolíneas)', 'tipo_dte' => 'FACT, FCAM', 'frase_automatica' => 'NA'],
            ['id' => 28, 'cod_escenario' => 22, 'id_frases' => 4, 'escenario' => 'Las notas de débito y crédito no deben incluir IVA cuando el documento origen al que hacen referencia tampoco lo incluye.', 'efecto' => 'NA', 'nombre' => 'Factura origen no incluye IVA', 'tipo_dte' => 'NCRE, NDEB', 'frase_automatica' => 'NA'],
            ['id' => 29, 'cod_escenario' => 23, 'id_frases' => 4, 'escenario' => 'La transferencia de dominio de bienes muebles, cuando el emisor del documento efectúe la aportación de bienes muebles a sociedades mercantiles.', 'efecto' => 'NA', 'nombre' => 'Exenta del IVA (art. 7, numeral 3, literal c, Ley del IVA)', 'tipo_dte' => 'FACT, FCAM', 'frase_automatica' => 'NA'],
            ['id' => 30, 'cod_escenario' => 24, 'id_frases' => 4, 'escenario' => 'Servicios no afectos, cuando el servicio es prestado fuera del territorio nacional y no se enmarca en el hecho generador del impuesto establecido en el artículo 3 y las exenciones según los artículos 7 y 8 del Decreto número 27-92 de la Ley del IVA.', 'efecto' => 'NA', 'nombre' => 'No afecto al IVA (Fuera del hecho generador art. 3, 7 y 8, Ley del IVA)', 'tipo_dte' => 'FACT, FCAM', 'frase_automatica' => 'NA'],
            ['id' => 31, 'cod_escenario' => 25, 'id_frases' => 4, 'escenario' => 'Ventas Zolic. Para el cumplimiento de sus fines, la institución gozará de la exención de impuestos, derechos y arbitrios fiscales o municipales, establecidos o que se establezcan.', 'efecto' => 'NA', 'nombre' => 'Exenta del IVA (art. 31 Dec. 22-73 Ley Orgánica Zolic)', 'tipo_dte' => 'FACT, FCAM', 'frase_automatica' => 'NA'],
            [
                "id" => 32,
                "cod_escenario" => 26,
                "id_frases" => 4,
                "escenario" => "Boletos aéreos para beneficiarios del Dec. 31-2022. Está exenta de IVA la compra de boletos aéreos que sean adquiridos exclusivamente  para las personas que trabajen fuera del territorio de guatemalteco contratados por empleadores extranjeros con el apoyo del Ministerio de Trabajo y Previsión Social, o por medio de un reclutador debidamente registrado en el Ministerio de Trabajo y Previsión Social. ",
                "efecto" => "NA",
                "nombre" => "Exenta del IVA (art. 4 Dec. 31-2022 Ley de Fom. del Trab. Temp. en el Extranjero) ",
                "tipo_dte" => "FACT, FCAM",
                "frase_automatica" => "NA",
            ],
            [
                "id" => 33,
                "cod_escenario" => 27,
                "id_frases" => 4,
                "escenario" => "Primera venta vehículo eléctrico, motocicleta eléctrica  o impulsado por hidrógeno.",
                "efecto" => "NA",
                "nombre" => "Exenta del IVA (art. 7 literal “a”  Dec. 40-2022 Ley Inc. Mov. Eléctrica)",
                "tipo_dte" => "FACT, FCAM",
                "frase_automatica" => "NA",
            ],
            [
                "id" => 34,
                "cod_escenario" => 28,
                "id_frases" => 4,
                "escenario" => "Primera venta vehículo eléctrico, motocicleta eléctrica, vehículo híbrido o impulsado por hidrógeno pesado o especial. ",
                "efecto" => "NA",
                "nombre" => "Exenta del IVA (art. 7 literal “c” Dec. 40-2022 Ley Inc. Mov. Eléctrica)",
                "tipo_dte" => "FACT, FCAM",
                "frase_automatica" => "NA",
            ],
            [
                "id" => 35,
                "cod_escenario" => 29,
                "id_frases" => 4,
                "escenario" => "Primera venta teleférico, funicular, tren eléctrico, tren ligero, tranvía o trolebús.",
                "efecto" => "NA",
                "nombre" => "Exenta del IVA (art. 7 literal “d” Dec. 40-2022 Ley Inc. Mov. Eléctrica)  \r\n",
                "tipo_dte" => "FACT, FCAM",
                "frase_automatica" => "NA",
            ],
            [
                "id" => 36,
                "cod_escenario" => 30,
                "id_frases" => 4,
                "escenario" => "Servicio de transporte público y transporte colectivo a través de vehículo eléctrico, vehículo híbrido, vehículo impulsado por hidrógeno y sistema de transporte eléctrico.",
                "efecto" => "NA",
                "nombre" => "Exenta del IVA (art. 7 literal “g” Dec. 40-2022 Ley Inc. Mov. Eléctrica) ",
                "tipo_dte" => "FACT, FCAM",
                "frase_automatica" => "NA",
            ],
            [
                "id" => 37,
                "cod_escenario" => 31,
                "id_frases" => 4,
                "escenario" => "Primera venta de componentes específicos del vehículo eléctrico, motocicleta eléctrica, sistema de transporte eléctrico o vehículo impulsado por hidrógeno, de cargador para vehículo o motocicleta eléctricos.",
                "efecto" => "NA",
                "nombre" => "Exenta del IVA (art. 7 literal “h” o “i” Dec. 402022 Ley Inc. Mov. Eléctrica) \r\n",
                "tipo_dte" => "FACT, FCAM",
                "frase_automatica" => "NA",
            ],
            [
                "id" => 38,
                "cod_escenario" => 32,
                "id_frases" => 4,
                "escenario" => "Contratos Leasing Dec. 2-2021 por Arrendadadoras relacionados a vehículos eléctricos, vehículo de hidrógeno, sistemas de transporte eléctrico teleférico, funicular, tren eléctrico, tren ligero, tranvía o trolebús, cargador para vehículo eléctrico y de hidrógeno, motor eléctrico para vehículo eléctrico y de hidrógeno, batería para motor eléctrico y de hidrógeno",
                "efecto" => "NA",
                "nombre" => "Exenta del IVA (art. 8 Dec. 40-2022 Ley Inc. Mov. Eléctrica",
                "tipo_dte" => "FACT, FCAM",
                "frase_automatica" => "NA",
            ],
            [
                "id" => 39,
                "cod_escenario" => 33,
                "id_frases" => 4,
                "escenario" => "Ingresos no afectos, obtenidos en concepto de cuotas cuyo destino específicamente para cubrir gastos comunes de administración, mantenimiento, reparaciones, de servicios generales y primas de seguros de edificios, efectuados por los condóminos.",
                "efecto" => "NA",
                "nombre" => "No afecto al IVA (Fuera del hecho generador art. 3, Ley del IVA",
                "tipo_dte" => "FACT, FCAM, RECI",
                "frase_automatica" => "NA",
            ],
            [
                "id" => 40,
                "cod_escenario" => 1,
                "id_frases" => 5,
                "escenario" => "Se incluirá la frase al DTE de tipo Factura Especial en las compras en las que el vendedor o prestador del servicio se niegue a emitir la factura correspondiente.\r\n",
                "efecto" => "N/A",
                "nombre" => "El vendedor o prestador del servicio se negó a emitir la factura correspondiente. (art. 52 Ley del IVA)",
                "tipo_dte" => "NA",
                "frase_automatica" => "NA",
            ],
            [
                "id" => 41,
                "cod_escenario" => 1,
                "id_frases" => 6,
                "escenario" => "El contribuyente está afiliado al IVA en el Régimen Especial de Contribuyente Agropecuario y su forma de pago del impuesto es el 5% sobre las ventas brutas",
                "efecto" => "NA",
                "nombre" => "Con forma de pago sobre las ventas brutas",
                "tipo_dte" => "NA",
                "frase_automatica" => "SI",
            ],
            [
                "id" => 42,
                "cod_escenario" => 2,
                "id_frases" => 6,
                "escenario" => "El contribuyente está afiliado al IVA en el Régimen Especial de Contribuyente Agropecuario y su forma de pago del impuesto es el 5% sobre las utilidades.\r\n",
                "efecto" => "NA",
                "nombre" => "Con forma de pago sobre las utilidades, no retener",
                "tipo_dte" => "NA",
                "frase_automatica" => "SI",
            ],
            [
                "id" => 43,
                "cod_escenario" => 1,
                "id_frases" => 7,
                "escenario" => "El contribuyente está afiliado al IVA en el Régimen electrónico de pequeño contribuyente.",
                "efecto" => "NA",
                "nombre" => "No retener, XXXXDonde XXXX corresponde al número de resolución de la afiliación especial del contribuyente emisor.",
                "tipo_dte" => "NA",
                "frase_automatica" => "SI",
            ],
            [
                "id" => 44,
                "cod_escenario" => 2,
                "id_frases" => 7,
                "escenario" => "El contribuyente está afiliado al IVA en el Régimen electrónico especial de contribuyente agropeguario",
                "efecto" => "NA",
                "nombre" => "No retener, XXXX*Donde XXXXcorresponde al número de resolución de la afiliación especial del contribuyente emisor.",
                "tipo_dte" => "NA",
                "frase_automatica" => "SI",
            ],
            [
                "id" => 45,
                "cod_escenario" => 1,
                "id_frases" => 8,
                "escenario" => "Exenciones generales universidades. Las universidades legalmente autorizadas para funcionar en el país.\r\n",
                "efecto" => "NA",
                "nombre" => "Exenta del ISR (art. 8 núm. 2 Ley de Actualización Tributaria)\r\n",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 46,
                "cod_escenario" => 2,
                "id_frases" => 8,
                "escenario" => "Exenciones generales centros educativos privados.Los centros educativos privados, como centros de cultura, exclusivamente en las rentas derivadas de: matrícula de inscripción, colegiaturas y derechos de examen, por los cursos que tengan autorizados por la autoridad competente.",
                "efecto" => "NA",
                "nombre" => "Exenta del ISR (art. 8 núm. 3 Ley de Actualización Tributaria)",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 47,
                "cod_escenario" => 3,
                "id_frases" => 8,
                "escenario" => "Exenciones generales iglesias. Exclusivamente por razón de culto.",
                "efecto" => "NA",
                "nombre" => "Exenta del ISR (art. 8 núm. 5 Ley de Actualización Tributaria)\r\n",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 48,
                "cod_escenario" => 4,
                "id_frases" => 8,
                "escenario" => "Exenciones Rentas de Actividades Lucrativas entes no lucrativos. Las rentas que obtengan los entes que destinen exclusivamente a los fines no lucrativos de su creación y en ningún caso distribuyan, directa o indirectamente, utilidades o bienes entre sus integrantes, tales como: los colegios profesionales; los partidos políticos; los comités cívicos; las asociaciones o fundaciones no lucrativas legalmente autorizadas e inscritas como exentas ante la Administración Tributaria, que tengan por objeto la beneficencia, asistencia o el servicio social, actividades culturales, científicas de educación e instrucción, artísticas, literarias, deportivas, políticas, sindicales, gremiales, religiosas, o el desarrollo de comunidades indígenas; únicamente por la parte que provenga de donaciones o cuotas ordinarias o extraordinarias.\r\n",
                "efecto" => "NA",
                "nombre" => "Exenta del ISR (art. 11 núm. 1 Ley de Actualización Tributaria)\r\n",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 49,
                "cod_escenario" => 5,
                "id_frases" => 8,
                "escenario" => "Exenciones Rentas de Actividades Lucrativas cooperativas. Las rentas de las cooperativas legalmente constituidas en el país, provenientes de las transacciones con sus asociados y con otras cooperativas, federaciones y confederaciones de cooperativas.",
                "efecto" => "NA",
                "nombre" => "Exenta del ISR (art. 11 núm. 2 Ley de Actualización Tributaria)",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 50,
                "cod_escenario" => 6,
                "id_frases" => 8,
                "escenario" => "Exenta ISR Zolic. Para el cumplimiento de sus fines, la institución gozará de la exención de impuestos, derechos y arbitrios fiscales o municipales, establecidos o que se establezcan",
                "efecto" => "NA",
                "nombre" => "Exenta del ISR (art. 31 Ley Orgánica Zolic)",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 51,
                "cod_escenario" => 7,
                "id_frases" => 8,
                "escenario" => "Exenta ISR Usuarios Zolic. Los usuarios que se instalen y operen dentro de la Zona Libre gozarán de exención del ISR por 10 años a partir de la fecha en que la empresa inicie sus operaciones dentro de la Zona Libre.",
                "efecto" => "NA",
                "nombre" => "Exenta del ISR (art. 32 litar a, Ley Orgánica Zolic",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 52,
                "cod_escenario" => 8,
                "id_frases" => 8,
                "escenario" => "Exenciones generales entidades del Estado. Los organismos del Estado y sus entidades descentralizadas, autónomas, las municipalidades y sus empresas.",
                "efecto" => "NA",
                "nombre" => "Exenta del ISR (art. 8 núm. 1 Ley de Actualización Tributaria)\r\n",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 53,
                "cod_escenario" => 9,
                "id_frases" => 8,
                "escenario" => "Exención por servicio de carga eléctrica a otros tipos de vehículos y transporte. Servicio de carga para vehículos eléctricos, hidrógeno y sistema de transporte eléctrico.",
                "efecto" => "NA",
                "nombre" => "Exenta del ISR (Art. 4, literal b), numeral ii, Dec. 40-2022, Ley Inc. Mov. Eléctrica)",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 54,
                "cod_escenario" => 10,
                "id_frases" => 8,
                "escenario" => "Exención por servicios de ensamblaje y/o producción a otros vehículos y transporte. Renta generada por ensamblaje y/o producción de vehículos hibridos, motocicleta eléctrica, vehículo impulsado por hidrógeno y sistema de transporte eléctrico.",
                "efecto" => "NA",
                "nombre" => "Exenta del ISR (Art. 7, literal f, Dec. 40-2022, Ley Inc. Mov. Eléctrica) ",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 55,
                "cod_escenario" => 11,
                "id_frases" => 8,
                "escenario" => "Exención a servicios de transporte público y colectivo. Prestación de servicios de transporte público y transporte colectivo a través de vehículos eléctricos, híbridos, impulsados por hidrógeno y sistema de transporte eléctrico.\r\n",
                "efecto" => "NA",
                "nombre" => "Exenta del ISR (Art. 7, literal g, Dec. 40-2022, Ley Inc. Mov. Eléctrica) ",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 56,
                "cod_escenario" => 12,
                "id_frases" => 8,
                "escenario" => "Rentas no afectas, obtenidos en conceptos de cuotas cuyo destino específicamente para cubrir gastos comunes de administración, mantenimiento, reparaciones, de servicios generales y primas de seguros de edificios, efectuados por los condóminos.",
                "efecto" => "NA",
                "nombre" => "No afecta al ISR (Fuera del hecho generador, arto. 10, Ley de Actualización Tributaria)",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 57,
                "cod_escenario" => 1,
                "id_frases" => 9,
                "escenario" => "Decreto XX-2022Las empresas envasadoras de Gas Propano deberán incluir la frase correspondiente al subsidio.",
                "efecto" => "NA",
                "nombre" => "Esta factura incluye apoyo social temporal al precio del gas licuado envasado en cilindros portátiles ( Dec. XX-2022) por un valor XXXXX",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 58,
                "cod_escenario" => 2,
                "id_frases" => 9,
                "escenario" => "Decreto 42-2022Las empresas importadoras de derivados de petroléo al vender Diésel deberán de incluir dicha frase.Observación dicha frase es obligatoria para los importadores de combustibles cuando utilicen el código de producto del apoyo social y para las distribuidoras (Gasolineras) cuando vendan estos dos productos.\r\n",
                "efecto" => "NA",
                "nombre" => "Esta factura incluye apoyo social temporal Decreto 42-2022 por un valor de GTQ –XXXX",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 59,
                "cod_escenario" => 3,
                "id_frases" => 9,
                "escenario" => "Decreto 42-2022Las empresas importadoras de derivados de petróleoal vender Diésel deberán incluir dicha frase.Observación dicha frase es obligatoria para los importadores de combustibles cuando utilicen el código de producto del apoyo social y para las distribuidoras (Gasolineras) cuando vendan el referido producto.",
                "efecto" => "NA",
                "nombre" => "Monto total a pagar sin apoyo social GTQ -XXX",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 60,
                "cod_escenario" => 4,
                "id_frases" => 9,
                "escenario" => "Impuesto de Salida Vía Aérea, cuando correspondaa personas guatemaltecas que laboren paraempleadores en el extranjero con registro decontratos en el Ministerio de Trabajo y PrevisiónSocial.",
                "efecto" => "NA",
                "nombre" => "Exenta Impuesto Salida Vía Aérea (art. 4 Dec. 31-2022 Ley de Fom. del Trab. Temp. en el Extranjero)\r\n",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 61,
                "cod_escenario" => 5,
                "id_frases" => 9,
                "escenario" => "Decreto 45-2022Las empresas envasadoras de Gas Propano deberán incluir la frase correspondiente al subsidio.\r\n",
                "efecto" => "NA",
                "nombre" => "Esta factura incluye apoyo social temporal al precio del gas licuado envasado en cilindros portátiles ( Dec. 45-2022) ",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 62,
                "cod_escenario" => 6,
                "id_frases" => 9,
                "escenario" => "Decreto 45-2022Las empresas envasadoras de Gas Propano deberánincluir la frase correspondiente al subsidio.",
                "efecto" => "NA",
                "nombre" => "Esta factura incluyeapoyo social temporalal precio del gaslicuado envasado encilindros portátiles (Dec. 45-2022 y susReformas)",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 63,
                "cod_escenario" => 7,
                "id_frases" => 9,
                "escenario" => "Decreto 05-2023Las empresas envasadoras de Gas Propano deberánincluir la frase correspondiente al subsidio.\r\n",
                "efecto" => "NA",
                "nombre" => "Esta factura incluye apoyo social temporal al precio del gas licuado envasado en cilindros portátiles (Dec. 5-2023)",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 64,
                "cod_escenario" => 8,
                "id_frases" => 9,
                "escenario" => "DTE (otros documentos):Cuando el contribuyente emite un documento que respalda el traslado de mercancías de un lugar a otro.\r\n",
                "efecto" => "NA",
                "nombre" => "La emisión de este documento no sustituye una factura",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 65,
                "cod_escenario" => 9,
                "id_frases" => 9,
                "escenario" => "DTE (otros documentos):Cuando el contribuyente emite un documento que respalda un pago como anticipo en una operación comercial.\r\n",
                "efecto" => "NA",
                "nombre" => "Este documento no constituye factura contable ni genera derecho a crédito fiscal del IVA",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ],
            [
                "id" => 66,
                "cod_escenario" => 10,
                "id_frases" => 9,
                "escenario" => "DTE (otros documentos):Cuando el contribuyente emite un documento que respalda un pago como anticipo en una operación comercial.",
                "efecto" => "NA",
                "nombre" => "Concluido el servicio, debe emitirse la factura, conforme la liquidación correspondiente.",
                "tipo_dte" => "NA",
                "frase_automatica" => "NO",
            ]
        ];

        foreach ($escenarios as $escenario) {
            Escenario::create($escenario);
        }
    }
}
