<?php

namespace Database\Seeders;

use App\Models\Municipio;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Municipio::insert([
            //Departamento de Guatemala
            ['id' => 1, 'codigo' => '0101', 'nombre' => 'Municipio de Guatemala', 'departamento_id' => 1],
            ['id' => 2, 'codigo' => '0102', 'nombre' => 'Santa Catarina Pinula', 'departamento_id' => 1],
            ['id' => 3, 'codigo' => '0103', 'nombre' => 'San José Pinula', 'departamento_id' => 1],
            ['id' => 4, 'codigo' => '0104', 'nombre' => 'San José del Golfo', 'departamento_id' => 1],
            ['id' => 5, 'codigo' => '0105', 'nombre' => 'Palencia', 'departamento_id' => 1],
            ['id' => 6, 'codigo' => '0106', 'nombre' => 'Chinautla', 'departamento_id' => 1],
            ['id' => 7, 'codigo' => '0107', 'nombre' => 'San Pedro Ayampuc', 'departamento_id' => 1],
            ['id' => 8, 'codigo' => '0108', 'nombre' => 'Mixco', 'departamento_id' => 1],
            ['id' => 9, 'codigo' => '0109', 'nombre' => 'San Pedro Sacatepéquez', 'departamento_id' => 1],
            ['id' => 10, 'codigo' => '0110', 'nombre' => 'San Juan Sacatepéquez', 'departamento_id' => 1],
            ['id' => 11, 'codigo' => '0111', 'nombre' => 'San Raimundo', 'departamento_id' => 1],
            ['id' => 12, 'codigo' => '0112', 'nombre' => 'Chuarrancho', 'departamento_id' => 1],
            ['id' => 13, 'codigo' => '0113', 'nombre' => 'Fraijanes', 'departamento_id' => 1],
            ['id' => 14, 'codigo' => '0114', 'nombre' => 'Amatitlán', 'departamento_id' => 1],
            ['id' => 15, 'codigo' => '0115', 'nombre' => 'Villa Nueva', 'departamento_id' => 1],
            ['id' => 16, 'codigo' => '0116', 'nombre' => 'Villa Canales', 'departamento_id' => 1],
            ['id' => 17, 'codigo' => '0117', 'nombre' => 'Petapa', 'departamento_id' => 1],

            // Departamento de El Progreso
            ['id' => 18, 'codigo' => '0201', 'nombre' => 'Guastatoya', 'departamento_id' => 2],
            ['id' => 19, 'codigo' => '0202', 'nombre' => 'Morazán', 'departamento_id' => 2],
            ['id' => 20, 'codigo' => '0203', 'nombre' => 'San Agustín Acasaguastlán', 'departamento_id' => 2],
            ['id' => 21, 'codigo' => '0204', 'nombre' => 'San Cristóbal Acasaguastlán', 'departamento_id' => 2],
            ['id' => 22, 'codigo' => '0205', 'nombre' => 'El Jícaro', 'departamento_id' => 2],
            ['id' => 23, 'codigo' => '0206', 'nombre' => 'Sansare', 'departamento_id' => 2],
            ['id' => 24, 'codigo' => '0207', 'nombre' => 'Sanarate', 'departamento_id' => 2],
            ['id' => 25, 'codigo' => '0208', 'nombre' => 'San Antonio La Paz', 'departamento_id' => 2],

            // Departamento de Sacatepéquez
            ['id' => 26, 'codigo' => '0301', 'nombre' => 'Antigua Guatemala', 'departamento_id' => 3],
            ['id' => 27, 'codigo' => '0302', 'nombre' => 'Jocotenango', 'departamento_id' => 3],
            ['id' => 28, 'codigo' => '0303', 'nombre' => 'Pastores', 'departamento_id' => 3],
            ['id' => 29, 'codigo' => '0304', 'nombre' => 'Sumpango', 'departamento_id' => 3],
            ['id' => 30, 'codigo' => '0305', 'nombre' => 'Santo Domingo Xenacoj', 'departamento_id' => 3],
            ['id' => 31, 'codigo' => '0306', 'nombre' => 'Santiago Sacatepéquez', 'departamento_id' => 3],
            ['id' => 32, 'codigo' => '0307', 'nombre' => 'San Bartolomé Milpas Altas', 'departamento_id' => 3],
            ['id' => 33, 'codigo' => '0308', 'nombre' => 'San Lucas Sacatepéquez', 'departamento_id' => 3],
            ['id' => 34, 'codigo' => '0309', 'nombre' => 'Santa Lucía Milpas Altas', 'departamento_id' => 3],
            ['id' => 35, 'codigo' => '0310', 'nombre' => 'Magdalena Milpas Altas', 'departamento_id' => 3],
            ['id' => 36, 'codigo' => '0311', 'nombre' => 'Santa María de Jesús', 'departamento_id' => 3],
            ['id' => 37, 'codigo' => '0312', 'nombre' => 'Ciudad Vieja', 'departamento_id' => 3],
            ['id' => 38, 'codigo' => '0313', 'nombre' => 'San Miguel Dueñas', 'departamento_id' => 3],
            ['id' => 39, 'codigo' => '0314', 'nombre' => 'Alotenango', 'departamento_id' => 3],
            ['id' => 40, 'codigo' => '0315', 'nombre' => 'San Antonio Aguas Calientes', 'departamento_id' => 3],
            ['id' => 41, 'codigo' => '0316', 'nombre' => 'Santa Catalina Barahona', 'departamento_id' => 3],

            // Departamento de Chimaltenango
            ['id' => 42, 'codigo' => '0401', 'nombre' => 'Chimaltenango', 'departamento_id' => 4],
            ['id' => 43, 'codigo' => '0402', 'nombre' => 'San José Poaquil', 'departamento_id' => 4],
            ['id' => 44, 'codigo' => '0403', 'nombre' => 'San Martín Jilotepeque', 'departamento_id' => 4],
            ['id' => 45, 'codigo' => '0404', 'nombre' => 'Comalapa', 'departamento_id' => 4],
            ['id' => 46, 'codigo' => '0405', 'nombre' => 'Santa Apolonia', 'departamento_id' => 4],
            ['id' => 47, 'codigo' => '0406', 'nombre' => 'Tecpán Guatemala', 'departamento_id' => 4],
            ['id' => 48, 'codigo' => '0407', 'nombre' => 'Patzún', 'departamento_id' => 4],
            ['id' => 49, 'codigo' => '0408', 'nombre' => 'Pochuta', 'departamento_id' => 4],
            ['id' => 50, 'codigo' => '0409', 'nombre' => 'Patzicía', 'departamento_id' => 4],
            ['id' => 51, 'codigo' => '0410', 'nombre' => 'Santa Cruz Balanyá', 'departamento_id' => 4],
            ['id' => 52, 'codigo' => '0411', 'nombre' => 'Acatenango', 'departamento_id' => 4],
            ['id' => 53, 'codigo' => '0412', 'nombre' => 'Yepocapa', 'departamento_id' => 4],
            ['id' => 54, 'codigo' => '0413', 'nombre' => 'San Andrés Itzapa', 'departamento_id' => 4],
            ['id' => 55, 'codigo' => '0414', 'nombre' => 'Parramos', 'departamento_id' => 4],
            ['id' => 56, 'codigo' => '0415', 'nombre' => 'Zaragoza', 'departamento_id' => 4],
            ['id' => 57, 'codigo' => '0416', 'nombre' => 'El Tejar', 'departamento_id' => 4],

            // Departamento de Escuintla
            ['id' => 58, 'codigo' => '0501', 'nombre' => 'Escuintla', 'departamento_id' => 5],
            ['id' => 59, 'codigo' => '0502', 'nombre' => 'Santa Lucía Cotzumalguapa', 'departamento_id' => 5],
            ['id' => 60, 'codigo' => '0503', 'nombre' => 'La Democracia', 'departamento_id' => 5],
            ['id' => 61, 'codigo' => '0504', 'nombre' => 'Siquinalá', 'departamento_id' => 5],
            ['id' => 62, 'codigo' => '0505', 'nombre' => 'Masagua', 'departamento_id' => 5],
            ['id' => 63, 'codigo' => '0506', 'nombre' => 'Tiquisate', 'departamento_id' => 5],
            ['id' => 64, 'codigo' => '0507', 'nombre' => 'La Gomera', 'departamento_id' => 5],
            ['id' => 65, 'codigo' => '0508', 'nombre' => 'Guanagazapa', 'departamento_id' => 5],
            ['id' => 66, 'codigo' => '0509', 'nombre' => 'San José', 'departamento_id' => 5],
            ['id' => 67, 'codigo' => '0510', 'nombre' => 'Iztapa', 'departamento_id' => 5],
            ['id' => 68, 'codigo' => '0511', 'nombre' => 'Palín', 'departamento_id' => 5],
            ['id' => 69, 'codigo' => '0512', 'nombre' => 'San Vicente Pacaya', 'departamento_id' => 5],
            ['id' => 70, 'codigo' => '0513', 'nombre' => 'Nueva Concepción', 'departamento_id' => 5],

            // Departamento de Santa Rosa
            ['id' => 71, 'codigo' => '0601', 'nombre' => 'Cuilapa', 'departamento_id' => 6],
            ['id' => 72, 'codigo' => '0602', 'nombre' => 'Barberena', 'departamento_id' => 6],
            ['id' => 73, 'codigo' => '0603', 'nombre' => 'Santa Rosa de Lima', 'departamento_id' => 6],
            ['id' => 74, 'codigo' => '0604', 'nombre' => 'Casillas', 'departamento_id' => 6],
            ['id' => 75, 'codigo' => '0605', 'nombre' => 'San Rafael Las Flores', 'departamento_id' => 6],
            ['id' => 76, 'codigo' => '0606', 'nombre' => 'Oratorio', 'departamento_id' => 6],
            ['id' => 77, 'codigo' => '0607', 'nombre' => 'San Juan Tecuaco', 'departamento_id' => 6],
            ['id' => 78, 'codigo' => '0608', 'nombre' => 'Chiquimulilla', 'departamento_id' => 6],
            ['id' => 79, 'codigo' => '0609', 'nombre' => 'Taxisco', 'departamento_id' => 6],
            ['id' => 80, 'codigo' => '0610', 'nombre' => 'Santa María Ixhuatán', 'departamento_id' => 6],
            ['id' => 81, 'codigo' => '0611', 'nombre' => 'Guazacapán', 'departamento_id' => 6],
            ['id' => 82, 'codigo' => '0612', 'nombre' => 'Santa Cruz Naranjo', 'departamento_id' => 6],
            ['id' => 83, 'codigo' => '0613', 'nombre' => 'Pueblo Nuevo Viñas', 'departamento_id' => 6],
            ['id' => 84, 'codigo' => '0614', 'nombre' => 'Nueva Santa Rosa', 'departamento_id' => 6],

            //Solola
            ['id' => 85, 'codigo' => '0701', 'nombre' => 'Sololá', 'departamento_id' => 7],
            ['id' => 86, 'codigo' => '0702', 'nombre' => 'San José Chacayá', 'departamento_id' => 7],
            ['id' => 87, 'codigo' => '0703', 'nombre' => 'Santa María Visitación', 'departamento_id' => 7],
            ['id' => 88, 'codigo' => '0704', 'nombre' => 'Santa Lucía Utatlán', 'departamento_id' => 7],
            ['id' => 89, 'codigo' => '0705', 'nombre' => 'Nahualá', 'departamento_id' => 7],
            ['id' => 90, 'codigo' => '0706', 'nombre' => 'Santa Catarina Ixtahuacan', 'departamento_id' => 7],
            ['id' => 91, 'codigo' => '0707', 'nombre' => 'Santa Clara La Laguna', 'departamento_id' => 7],
            ['id' => 92, 'codigo' => '0708', 'nombre' => 'Concepción', 'departamento_id' => 7],
            ['id' => 93, 'codigo' => '0709', 'nombre' => 'San Andrés Semetabaj', 'departamento_id' => 7],
            ['id' => 94, 'codigo' => '0710', 'nombre' => 'Panajachel', 'departamento_id' => 7],
            ['id' => 95, 'codigo' => '0711', 'nombre' => 'Santa Catarina Palopó', 'departamento_id' => 7],
            ['id' => 96, 'codigo' => '0712', 'nombre' => 'San Antonio Palopó', 'departamento_id' => 7],
            ['id' => 97, 'codigo' => '0713', 'nombre' => 'San Lucas Tolimán', 'departamento_id' => 7],
            ['id' => 98, 'codigo' => '0714', 'nombre' => 'Santa Cruz La Laguna', 'departamento_id' => 7],
            ['id' => 99, 'codigo' => '0715', 'nombre' => 'San Pablo La Laguna', 'departamento_id' => 7],
            ['id' => 100, 'codigo' => '0716', 'nombre' => 'San Marcos La Laguna', 'departamento_id' => 7],
            ['id' => 101, 'codigo' => '0717', 'nombre' => 'San Juan La Laguna', 'departamento_id' => 7],
            ['id' => 102, 'codigo' => '0718', 'nombre' => 'San Pedro La Laguna', 'departamento_id' => 7],
            ['id' => 103, 'codigo' => '0719', 'nombre' => 'Santiago Atitlán', 'departamento_id' => 7],

            //Totonicapan
            ['id' => 104, 'codigo' => '0801', 'nombre' => 'Totonicapán', 'departamento_id' => 8],
            ['id' => 105, 'codigo' => '0802', 'nombre' => 'San Cristóbal Totonicapán', 'departamento_id' => 8],
            ['id' => 106, 'codigo' => '0803', 'nombre' => 'San Francisco El Alto', 'departamento_id' => 8],
            ['id' => 107, 'codigo' => '0804', 'nombre' => 'San Andrés Xecul', 'departamento_id' => 8],
            ['id' => 108, 'codigo' => '0805', 'nombre' => 'Momostenango', 'departamento_id' => 8],
            ['id' => 109, 'codigo' => '0806', 'nombre' => 'Santa María Chiquimula', 'departamento_id' => 8],
            ['id' => 110, 'codigo' => '0807', 'nombre' => 'Santa Lucía La Reforma', 'departamento_id' => 8],
            ['id' => 111, 'codigo' => '0808', 'nombre' => 'San Bartolo', 'departamento_id' => 8],

            //Quetzaltenango
            ['id' => 112, 'codigo' => '0901', 'nombre' => 'Quetzaltenango', 'departamento_id' => 9],
            ['id' => 113, 'codigo' => '0902', 'nombre' => 'Salcajá', 'departamento_id' => 9],
            ['id' => 114, 'codigo' => '0903', 'nombre' => 'Olintepeque', 'departamento_id' => 9],
            ['id' => 115, 'codigo' => '0904', 'nombre' => 'San Carlos Sija', 'departamento_id' => 9],
            ['id' => 116, 'codigo' => '0905', 'nombre' => 'Sibilia', 'departamento_id' => 9],
            ['id' => 117, 'codigo' => '0906', 'nombre' => 'Cabricán', 'departamento_id' => 9],
            ['id' => 118, 'codigo' => '0907', 'nombre' => 'Cajolá', 'departamento_id' => 9],
            ['id' => 119, 'codigo' => '0908', 'nombre' => 'San Miguel Sigüilá', 'departamento_id' => 9],
            ['id' => 120, 'codigo' => '0909', 'nombre' => 'Ostuncalco', 'departamento_id' => 9],
            ['id' => 121, 'codigo' => '0910', 'nombre' => 'San Mateo', 'departamento_id' => 9],
            ['id' => 122, 'codigo' => '0911', 'nombre' => 'Concepción Chiquirichapa', 'departamento_id' => 9],
            ['id' => 123, 'codigo' => '0912', 'nombre' => 'San Martín Sacatepéquez', 'departamento_id' => 9],
            ['id' => 124, 'codigo' => '0913', 'nombre' => 'Almolonga', 'departamento_id' => 9],
            ['id' => 125, 'codigo' => '0914', 'nombre' => 'Cantel', 'departamento_id' => 9],
            ['id' => 126, 'codigo' => '0915', 'nombre' => 'Huitán', 'departamento_id' => 9],
            ['id' => 127, 'codigo' => '0916', 'nombre' => 'Zunil', 'departamento_id' => 9],
            ['id' => 128, 'codigo' => '0917', 'nombre' => 'Colomba', 'departamento_id' => 9],
            ['id' => 129, 'codigo' => '0918', 'nombre' => 'San Francisco La Unión', 'departamento_id' => 9],
            ['id' => 130, 'codigo' => '0919', 'nombre' => 'El Palmar', 'departamento_id' => 9],
            ['id' => 131, 'codigo' => '0920', 'nombre' => 'Coatepeque', 'departamento_id' => 9],
            ['id' => 132, 'codigo' => '0921', 'nombre' => 'Génova', 'departamento_id' => 9],
            ['id' => 133, 'codigo' => '0922', 'nombre' => 'Flores Costa Cuca', 'departamento_id' => 9],
            ['id' => 134, 'codigo' => '0923', 'nombre' => 'La Esperanza', 'departamento_id' => 9],
            ['id' => 135, 'codigo' => '0924', 'nombre' => 'Palestina de los Altos', 'departamento_id' => 9],

            //Suchitepéquez 
            ['id' => 136, 'codigo' => '1001', 'nombre' => 'Mazatenango', 'departamento_id' => 10],
            ['id' => 137, 'codigo' => '1002', 'nombre' => 'Cuyotenango', 'departamento_id' => 10],
            ['id' => 138, 'codigo' => '1003', 'nombre' => 'San Francisco Zapotitlán', 'departamento_id' => 10],
            ['id' => 139, 'codigo' => '1004', 'nombre' => 'San Bernardino', 'departamento_id' => 10],
            ['id' => 140, 'codigo' => '1005', 'nombre' => 'San José El Idolo', 'departamento_id' => 10],
            ['id' => 141, 'codigo' => '1006', 'nombre' => 'Santo Domingo Suchitepequez', 'departamento_id' => 10],
            ['id' => 142, 'codigo' => '1007', 'nombre' => 'San Lorenzo', 'departamento_id' => 10],
            ['id' => 143, 'codigo' => '1008', 'nombre' => 'Samayac', 'departamento_id' => 10],
            ['id' => 144, 'codigo' => '1009', 'nombre' => 'San Pablo Jocopilas', 'departamento_id' => 10],
            ['id' => 145, 'codigo' => '1010', 'nombre' => 'San Antonio Suchitepequez', 'departamento_id' => 10],
            ['id' => 146, 'codigo' => '1011', 'nombre' => 'San Miguel Panan', 'departamento_id' => 10],
            ['id' => 147, 'codigo' => '1012', 'nombre' => 'San Gabriel', 'departamento_id' => 10],
            ['id' => 148, 'codigo' => '1013', 'nombre' => 'Chicacao', 'departamento_id' => 10],
            ['id' => 149, 'codigo' => '1014', 'nombre' => 'Patulul', 'departamento_id' => 10],
            ['id' => 150, 'codigo' => '1015', 'nombre' => 'Santa Barbara', 'departamento_id' => 10],
            ['id' => 151, 'codigo' => '1016', 'nombre' => 'San Juan Bautista', 'departamento_id' => 10],
            ['id' => 152, 'codigo' => '1017', 'nombre' => 'Santo Tomás La Unión', 'departamento_id' => 10],
            ['id' => 153, 'codigo' => '1018', 'nombre' => 'Zunilito', 'departamento_id' => 10],
            ['id' => 154, 'codigo' => '1019', 'nombre' => 'Pueblo Nuevo', 'departamento_id' => 10],
            ['id' => 155, 'codigo' => '1020', 'nombre' => 'Río Bravo', 'departamento_id' => 10],

            // Municipios de Retalhuleu 
            ['id' => 156, 'codigo' => '1101', 'nombre' => 'Retalhuleu', 'departamento_id' => 11],
            ['id' => 157, 'codigo' => '1102', 'nombre' => 'San Sebastián', 'departamento_id' => 11],
            ['id' => 158, 'codigo' => '1103', 'nombre' => 'Santa Cruz Muluá', 'departamento_id' => 11],
            ['id' => 159, 'codigo' => '1104', 'nombre' => 'San Martín Zapotitlán', 'departamento_id' => 11],
            ['id' => 160, 'codigo' => '1105', 'nombre' => 'San Felipe', 'departamento_id' => 11],
            ['id' => 161, 'codigo' => '1106', 'nombre' => 'San Andrés Villa Seca', 'departamento_id' => 11],
            ['id' => 162, 'codigo' => '1107', 'nombre' => 'Champerico', 'departamento_id' => 11],
            ['id' => 163, 'codigo' => '1108', 'nombre' => 'Nuevo San Carlos', 'departamento_id' => 11],
            ['id' => 164, 'codigo' => '1109', 'nombre' => 'El Asintal', 'departamento_id' => 11],

            //San marcos
            ['id' => 165, 'codigo' => '1201', 'nombre' => 'San Marcos', 'departamento_id' => 12],
            ['id' => 166, 'codigo' => '1202', 'nombre' => 'San Pedro Sacatepéquez', 'departamento_id' => 12],
            ['id' => 167, 'codigo' => '1203', 'nombre' => 'San Antonio Sacatepéquez', 'departamento_id' => 12],
            ['id' => 168, 'codigo' => '1204', 'nombre' => 'Comitancillo', 'departamento_id' => 12],
            ['id' => 169, 'codigo' => '1205', 'nombre' => 'San Miguel Ixtahuacán', 'departamento_id' => 12],
            ['id' => 170, 'codigo' => '1206', 'nombre' => 'Concepción Tutuapa', 'departamento_id' => 12],
            ['id' => 171, 'codigo' => '1207', 'nombre' => 'Tacaná', 'departamento_id' => 12],
            ['id' => 172, 'codigo' => '1208', 'nombre' => 'Sibinal', 'departamento_id' => 12],
            ['id' => 173, 'codigo' => '1209', 'nombre' => 'Tajumulco', 'departamento_id' => 12],
            ['id' => 174, 'codigo' => '1210', 'nombre' => 'Tejutla', 'departamento_id' => 12],
            ['id' => 175, 'codigo' => '1211', 'nombre' => 'San Rafael Pie De La Cuesta', 'departamento_id' => 12],
            ['id' => 176, 'codigo' => '1212', 'nombre' => 'Nuevo Progreso', 'departamento_id' => 12],
            ['id' => 177, 'codigo' => '1213', 'nombre' => 'El Tumbador', 'departamento_id' => 12],
            ['id' => 178, 'codigo' => '1214', 'nombre' => 'El Rodeo', 'departamento_id' => 12],
            ['id' => 179, 'codigo' => '1215', 'nombre' => 'Malacatán', 'departamento_id' => 12],
            ['id' => 180, 'codigo' => '1216', 'nombre' => 'Catarina', 'departamento_id' => 12],
            ['id' => 181, 'codigo' => '1217', 'nombre' => 'Ayutla', 'departamento_id' => 12],
            ['id' => 182, 'codigo' => '1218', 'nombre' => 'Ocós', 'departamento_id' => 12],
            ['id' => 183, 'codigo' => '1219', 'nombre' => 'San Pablo', 'departamento_id' => 12],
            ['id' => 184, 'codigo' => '1220', 'nombre' => 'El Quetzal', 'departamento_id' => 12],
            ['id' => 185, 'codigo' => '1221', 'nombre' => 'La Reforma', 'departamento_id' => 12],
            ['id' => 186, 'codigo' => '1222', 'nombre' => 'Pajapita', 'departamento_id' => 12],
            ['id' => 187, 'codigo' => '1223', 'nombre' => 'Ixchiguán', 'departamento_id' => 12],
            ['id' => 188, 'codigo' => '1224', 'nombre' => 'San José Ojetenam', 'departamento_id' => 12],
            ['id' => 189, 'codigo' => '1225', 'nombre' => 'San Cristóbal Cucho', 'departamento_id' => 12],
            ['id' => 190, 'codigo' => '1226', 'nombre' => 'Sipacapa', 'departamento_id' => 12],
            ['id' => 191, 'codigo' => '1227', 'nombre' => 'Esquipulas Palo Gordo', 'departamento_id' => 12],
            ['id' => 192, 'codigo' => '1228', 'nombre' => 'Río Blanco', 'departamento_id' => 12],
            ['id' => 193, 'codigo' => '1229', 'nombre' => 'San Lorenzo', 'departamento_id' => 12],

            //Huehuetenango
            ['id' => 194, 'codigo' => '1301', 'nombre' => 'Huehuetenango', 'departamento_id' => 13],
            ['id' => 195, 'codigo' => '1302', 'nombre' => 'Chiantla', 'departamento_id' => 13],
            ['id' => 196, 'codigo' => '1303', 'nombre' => 'Malacatancito', 'departamento_id' => 13],
            ['id' => 197, 'codigo' => '1304', 'nombre' => 'Cuilco', 'departamento_id' => 13],
            ['id' => 198, 'codigo' => '1305', 'nombre' => 'Nentón', 'departamento_id' => 13],
            ['id' => 199, 'codigo' => '1306', 'nombre' => 'San Pedro Necta', 'departamento_id' => 13],
            ['id' => 200, 'codigo' => '1307', 'nombre' => 'Jacaltenango', 'departamento_id' => 13],
            ['id' => 201, 'codigo' => '1308', 'nombre' => 'Soloma', 'departamento_id' => 13],
            ['id' => 202, 'codigo' => '1309', 'nombre' => 'Ixtahuacán', 'departamento_id' => 13],
            ['id' => 203, 'codigo' => '1310', 'nombre' => 'Santa Bárbara', 'departamento_id' => 13],
            ['id' => 204, 'codigo' => '1311', 'nombre' => 'La Libertad', 'departamento_id' => 13],
            ['id' => 205, 'codigo' => '1312', 'nombre' => 'La Democracia', 'departamento_id' => 13],
            ['id' => 206, 'codigo' => '1313', 'nombre' => 'San Miguel Acatán', 'departamento_id' => 13],
            ['id' => 207, 'codigo' => '1314', 'nombre' => 'San Rafael La Independencia', 'departamento_id' => 13],
            ['id' => 208, 'codigo' => '1315', 'nombre' => 'Todos Santos Cuchumatánes', 'departamento_id' => 13],
            ['id' => 209, 'codigo' => '1316', 'nombre' => 'San Juan Atitán', 'departamento_id' => 13],
            ['id' => 210, 'codigo' => '1317', 'nombre' => 'Santa Eulalia', 'departamento_id' => 13],
            ['id' => 211, 'codigo' => '1318', 'nombre' => 'San Mateo Ixtatán', 'departamento_id' => 13],
            ['id' => 212, 'codigo' => '1319', 'nombre' => 'Colotenango', 'departamento_id' => 13],
            ['id' => 213, 'codigo' => '1320', 'nombre' => 'San Sebastián Huehuetenango', 'departamento_id' => 13],
            ['id' => 214, 'codigo' => '1321', 'nombre' => 'Tectitán', 'departamento_id' => 13],
            ['id' => 215, 'codigo' => '1322', 'nombre' => 'Concepción Huista', 'departamento_id' => 13],
            ['id' => 216, 'codigo' => '1323', 'nombre' => 'San Juan Ixcoy', 'departamento_id' => 13],
            ['id' => 217, 'codigo' => '1324', 'nombre' => 'San Antonio Huista', 'departamento_id' => 13],
            ['id' => 218, 'codigo' => '1325', 'nombre' => 'San Sebastián Coatán', 'departamento_id' => 13],
            ['id' => 219, 'codigo' => '1326', 'nombre' => 'Barillas', 'departamento_id' => 13],
            ['id' => 220, 'codigo' => '1327', 'nombre' => 'Aguacatán', 'departamento_id' => 13],
            ['id' => 221, 'codigo' => '1328', 'nombre' => 'San Rafael Petzal', 'departamento_id' => 13],
            ['id' => 222, 'codigo' => '1329', 'nombre' => 'San Gaspar Ixchil', 'departamento_id' => 13],
            ['id' => 223, 'codigo' => '1330', 'nombre' => 'Santiago Chimaltenango', 'departamento_id' => 13],
            ['id' => 224, 'codigo' => '1331', 'nombre' => 'Santa Ana Huista', 'departamento_id' => 13],

            // Municipios de El Quiché 
            ['id' => 225, 'codigo' => '1401', 'nombre' => 'Santa Cruz del Quiché', 'departamento_id' => 14],
            ['id' => 226, 'codigo' => '1402', 'nombre' => 'Chiché', 'departamento_id' => 14],
            ['id' => 227, 'codigo' => '1403', 'nombre' => 'Chinique', 'departamento_id' => 14],
            ['id' => 228, 'codigo' => '1404', 'nombre' => 'Zacualpa', 'departamento_id' => 14],
            ['id' => 229, 'codigo' => '1405', 'nombre' => 'Chajul', 'departamento_id' => 14],
            ['id' => 230, 'codigo' => '1406', 'nombre' => 'Chichicastenango', 'departamento_id' => 14],
            ['id' => 231, 'codigo' => '1407', 'nombre' => 'Patzité', 'departamento_id' => 14],
            ['id' => 232, 'codigo' => '1408', 'nombre' => 'San Antonio Ilotenango', 'departamento_id' => 14],
            ['id' => 233, 'codigo' => '1409', 'nombre' => 'San Pedro Jocopilas', 'departamento_id' => 14],
            ['id' => 234, 'codigo' => '1410', 'nombre' => 'Cunén', 'departamento_id' => 14],
            ['id' => 235, 'codigo' => '1411', 'nombre' => 'San Juan Cotzal', 'departamento_id' => 14],
            ['id' => 236, 'codigo' => '1412', 'nombre' => 'Joyabaj', 'departamento_id' => 14],
            ['id' => 237, 'codigo' => '1413', 'nombre' => 'Nebaj', 'departamento_id' => 14],
            ['id' => 238, 'codigo' => '1414', 'nombre' => 'San Andrés Sajcabajá', 'departamento_id' => 14],
            ['id' => 239, 'codigo' => '1415', 'nombre' => 'Uspantán', 'departamento_id' => 14],
            ['id' => 240, 'codigo' => '1416', 'nombre' => 'Sacapulas', 'departamento_id' => 14],
            ['id' => 241, 'codigo' => '1417', 'nombre' => 'San Bartolomé Jocotenango', 'departamento_id' => 14],
            ['id' => 242, 'codigo' => '1418', 'nombre' => 'Canillá', 'departamento_id' => 14],
            ['id' => 243, 'codigo' => '1419', 'nombre' => 'Chicamán', 'departamento_id' => 14],
            ['id' => 244, 'codigo' => '1420', 'nombre' => 'Ixcán', 'departamento_id' => 14],
            ['id' => 245, 'codigo' => '1421', 'nombre' => 'Pachalum', 'departamento_id' => 14],

            // Municipios de Baja Verapaz 
            ['id' => 246, 'codigo' => '1501', 'nombre' => 'Salamá', 'departamento_id' => 15],
            ['id' => 247, 'codigo' => '1502', 'nombre' => 'San Miguel Chicaj', 'departamento_id' => 15],
            ['id' => 248, 'codigo' => '1503', 'nombre' => 'Rabinal', 'departamento_id' => 15],
            ['id' => 249, 'codigo' => '1504', 'nombre' => 'Cubulco', 'departamento_id' => 15],
            ['id' => 250, 'codigo' => '1505', 'nombre' => 'Granados', 'departamento_id' => 15],
            ['id' => 251, 'codigo' => '1506', 'nombre' => 'El Chol', 'departamento_id' => 15],
            ['id' => 252, 'codigo' => '1507', 'nombre' => 'San Jerónimo', 'departamento_id' => 15],
            ['id' => 253, 'codigo' => '1508', 'nombre' => 'Purulhá', 'departamento_id' => 15],

            // Municipios de Alta Verapaz 
            ['id' => 254, 'codigo' => '1601', 'nombre' => 'Cobán', 'departamento_id' => 16],
            ['id' => 255, 'codigo' => '1602', 'nombre' => 'Santa Cruz Verapaz', 'departamento_id' => 16],
            ['id' => 256, 'codigo' => '1603', 'nombre' => 'San Cristóbal Verapaz', 'departamento_id' => 16],
            ['id' => 257, 'codigo' => '1604', 'nombre' => 'Tactic', 'departamento_id' => 16],
            ['id' => 258, 'codigo' => '1605', 'nombre' => 'Tamahú', 'departamento_id' => 16],
            ['id' => 259, 'codigo' => '1606', 'nombre' => 'Tucurú', 'departamento_id' => 16],
            ['id' => 260, 'codigo' => '1607', 'nombre' => 'Panzós', 'departamento_id' => 16],
            ['id' => 261, 'codigo' => '1608', 'nombre' => 'Senahú', 'departamento_id' => 16],
            ['id' => 262, 'codigo' => '1609', 'nombre' => 'San Pedro Carchá', 'departamento_id' => 16],
            ['id' => 263, 'codigo' => '1610', 'nombre' => 'San Juan Chamelco', 'departamento_id' => 16],
            ['id' => 264, 'codigo' => '1611', 'nombre' => 'Lanquín', 'departamento_id' => 16],
            ['id' => 265, 'codigo' => '1612', 'nombre' => 'Cahabón', 'departamento_id' => 16],
            ['id' => 266, 'codigo' => '1613', 'nombre' => 'Chisec', 'departamento_id' => 16],
            ['id' => 267, 'codigo' => '1614', 'nombre' => 'Chahal', 'departamento_id' => 16],
            ['id' => 268, 'codigo' => '1615', 'nombre' => 'Fray Bartolomé de Las Casas', 'departamento_id' => 16],

            // Municipios de El Petén 
            ['id' => 269, 'codigo' => '1701', 'nombre' => 'Flores', 'departamento_id' => 17],
            ['id' => 270, 'codigo' => '1702', 'nombre' => 'San José', 'departamento_id' => 17],
            ['id' => 271, 'codigo' => '1703', 'nombre' => 'San Benito', 'departamento_id' => 17],
            ['id' => 272, 'codigo' => '1704', 'nombre' => 'San Andrés', 'departamento_id' => 17],
            ['id' => 273, 'codigo' => '1705', 'nombre' => 'La Libertad', 'departamento_id' => 17],
            ['id' => 274, 'codigo' => '1706', 'nombre' => 'San Francisco', 'departamento_id' => 17],
            ['id' => 275, 'codigo' => '1707', 'nombre' => 'Santa Ana', 'departamento_id' => 17],
            ['id' => 276, 'codigo' => '1708', 'nombre' => 'Dolores', 'departamento_id' => 17],
            ['id' => 277, 'codigo' => '1709', 'nombre' => 'San Luis', 'departamento_id' => 17],
            ['id' => 278, 'codigo' => '1710', 'nombre' => 'Sayaxché', 'departamento_id' => 17],
            ['id' => 279, 'codigo' => '1711', 'nombre' => 'Melchor De Mencos', 'departamento_id' => 17],
            ['id' => 280, 'codigo' => '1712', 'nombre' => 'Poptún', 'departamento_id' => 17],

            // Municipios de Izabal 
            ['id' => 281, 'codigo' => '1801', 'nombre' => 'Puerto Barrios', 'departamento_id' => 18],
            ['id' => 282, 'codigo' => '1802', 'nombre' => 'Livingston', 'departamento_id' => 18],
            ['id' => 283, 'codigo' => '1803', 'nombre' => 'El Estor', 'departamento_id' => 18],
            ['id' => 284, 'codigo' => '1804', 'nombre' => 'Morales', 'departamento_id' => 18],
            ['id' => 285, 'codigo' => '1805', 'nombre' => 'Los Amates', 'departamento_id' => 18],

            // Municipios de Zacapa 
            ['id' => 286, 'codigo' => '1901', 'nombre' => 'Zacapa', 'departamento_id' => 19],
            ['id' => 287, 'codigo' => '1902', 'nombre' => 'Estanzuela', 'departamento_id' => 19],
            ['id' => 288, 'codigo' => '1903', 'nombre' => 'Río Hondo', 'departamento_id' => 19],
            ['id' => 289, 'codigo' => '1904', 'nombre' => 'Gualán', 'departamento_id' => 19],
            ['id' => 290, 'codigo' => '1905', 'nombre' => 'Teculután', 'departamento_id' => 19],
            ['id' => 291, 'codigo' => '1906', 'nombre' => 'Usumatlán', 'departamento_id' => 19],
            ['id' => 292, 'codigo' => '1907', 'nombre' => 'Cabañas', 'departamento_id' => 19],
            ['id' => 293, 'codigo' => '1908', 'nombre' => 'San Diego', 'departamento_id' => 19],
            ['id' => 294, 'codigo' => '1909', 'nombre' => 'La Unión', 'departamento_id' => 19],
            ['id' => 295, 'codigo' => '1910', 'nombre' => 'Huité', 'departamento_id' => 19],

            // Municipios de Chiquimula 
            ['id' => 296, 'codigo' => '2001', 'nombre' => 'Chiquimula', 'departamento_id' => 20],
            ['id' => 297, 'codigo' => '2002', 'nombre' => 'San José La Arada', 'departamento_id' => 20],
            ['id' => 298, 'codigo' => '2003', 'nombre' => 'San Juan Ermita', 'departamento_id' => 20],
            ['id' => 299, 'codigo' => '2004', 'nombre' => 'Jocotán', 'departamento_id' => 20],
            ['id' => 300, 'codigo' => '2005', 'nombre' => 'Camotán', 'departamento_id' => 20],
            ['id' => 301, 'codigo' => '2006', 'nombre' => 'Olopa', 'departamento_id' => 20],
            ['id' => 302, 'codigo' => '2007', 'nombre' => 'Esquipulas', 'departamento_id' => 20],
            ['id' => 303, 'codigo' => '2008', 'nombre' => 'Concepción Las Minas', 'departamento_id' => 20],
            ['id' => 304, 'codigo' => '2009', 'nombre' => 'Quezaltepeque', 'departamento_id' => 20],
            ['id' => 305, 'codigo' => '2010', 'nombre' => 'San Jacinto', 'departamento_id' => 20],
            ['id' => 306, 'codigo' => '2011', 'nombre' => 'Ipala', 'departamento_id' => 20],

            // Municipios de Jalapa 
            ['id' => 307, 'codigo' => '2101', 'nombre' => 'Jalapa', 'departamento_id' => 21],
            ['id' => 308, 'codigo' => '2102', 'nombre' => 'San Pedro Pinula', 'departamento_id' => 21],
            ['id' => 309, 'codigo' => '2103', 'nombre' => 'San Luis Jilotepeque', 'departamento_id' => 21],
            ['id' => 310, 'codigo' => '2104', 'nombre' => 'San Manuel Chaparrón', 'departamento_id' => 21],
            ['id' => 311, 'codigo' => '2105', 'nombre' => 'San Carlos Alzatate', 'departamento_id' => 21],
            ['id' => 312, 'codigo' => '2106', 'nombre' => 'Monjas', 'departamento_id' => 21],
            ['id' => 313, 'codigo' => '2107', 'nombre' => 'Mataquescuintla', 'departamento_id' => 21],

            //Jutiapa
            ['id' => 314, 'codigo' => '2201', 'nombre' => 'Jutiapa', 'departamento_id' => 22],
            ['id' => 315, 'codigo' => '2202', 'nombre' => 'El Progreso', 'departamento_id' => 22],
            ['id' => 316, 'codigo' => '2203', 'nombre' => 'Santa Catarina Mita', 'departamento_id' => 22],
            ['id' => 317, 'codigo' => '2204', 'nombre' => 'Agua Blanca', 'departamento_id' => 22],
            ['id' => 318, 'codigo' => '2205', 'nombre' => 'Asunción Mita', 'departamento_id' => 22],
            ['id' => 319, 'codigo' => '2206', 'nombre' => 'Yupiltepeque', 'departamento_id' => 22],
            ['id' => 320, 'codigo' => '2207', 'nombre' => 'Atescatempa', 'departamento_id' => 22],
            ['id' => 321, 'codigo' => '2208', 'nombre' => 'Jerez', 'departamento_id' => 22],
            ['id' => 322, 'codigo' => '2209', 'nombre' => 'El Adelanto', 'departamento_id' => 22],
            ['id' => 323, 'codigo' => '2210', 'nombre' => 'Zapotitlán', 'departamento_id' => 22],
            ['id' => 324, 'codigo' => '2211', 'nombre' => 'Comapa', 'departamento_id' => 22],
            ['id' => 325, 'codigo' => '2212', 'nombre' => 'Jalpatagua', 'departamento_id' => 22],
            ['id' => 326, 'codigo' => '2213', 'nombre' => 'Conguaco', 'departamento_id' => 22],
            ['id' => 327, 'codigo' => '2214', 'nombre' => 'Moyuta', 'departamento_id' => 22],
            ['id' => 328, 'codigo' => '2215', 'nombre' => 'Pasaco', 'departamento_id' => 22],
            ['id' => 329, 'codigo' => '2216', 'nombre' => 'San José Acatempa', 'departamento_id' => 22],
            ['id' => 330, 'codigo' => '2217', 'nombre' => 'Quesada', 'departamento_id' => 22],
        ]);
    }
}
