<?php

namespace Database\Seeders;

use App\Models\TipoDte;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TiposDteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tiposDte = [
            ['id' => 1, 'nombre' => 'Factura', 'codigo' => 'FACT', 'descripcion' => 'Documento que los contribuyentes afectos al IVA están obligados a emitir y entregar al adquirente, por las ventas, permutas, arrendamientos, retiros, destrucción, pérdida, o cualquier hecho que implique faltante de inventario cuando constituya hecho generador de este impuesto, y por los servicios que presten los contribuyentes afectos, incluso respecto de lasoperaciones exentas o con personas exentas. Base legal: Decreto 27-92, Ley del IVA, artículo 29, literal a.'],
            ['id' => 2, 'nombre' => 'Factura Cambiaria', 'codigo' => 'FCAM', 'descripcion' => 'Documento que emite un vendedor de mercaderías. El comprador lo devuelve debidamente aceptado, quedando obligado a pagar a su vencimiento la suma pactada. Es un título de crédito a favor del vendedor.Base legal: a) Decreto 2-70, Código de Comercio, art. 591; b) Decreto 47-2008, Ley para el Reconocimiento de las Comunicaciones y Firmas Electrónicas, artículos 2 “Comercio Electrónico”, 7 y 9.'],
            ['id' => 3, 'nombre' => 'Factura Pequeño Contribuyente', 'codigo' => 'FPEQ', 'descripcion' => 'Documento que emite un contribuyente afiliado al Régimen de Pequeño Contribuyente. Base legal: Decreto 27-92, Ley del IVA, artículo 29, literal b'],
            ['id' => 4, 'nombre' => 'Factura Cambiaria Pequeño Contribuyente', 'codigo' => 'FCAP', 'descripcion' => 'Documento que emite un vendedor de mercaderías afiliado al Régimen de Pequeño Contribuyente. El comprador lo devuelve debidamente aceptado, quedando obligado a pagar a su vencimiento la suma pactada. Es un título de crédito a favor del vendedor. Base legal: a) Decreto 2-70, Código de Comercio, artículo 591; b) Decreto 47-2008, Ley para el Reconocimiento de las Comunicaciones y Firmas Electrónicas, artículos 2 “Comercio Electrónico”, 7 y 9.'],
            ['id' => 5, 'nombre' => 'Factura Especial', 'codigo' => 'FESP', 'descripcion' => 'a) Documento que emite un comprador por cuenta del vendedor o prestador del servicio, que por la naturaleza de sus actividades o cualquier otra circunstancia, no extiende la factura correspondiente.  b) Documento que emite un comprador exportador cuando el vendedor no se encuentra registrado en la SAT como productor autorizado de productos agropecuarios, artesanales y productos reciclados. El comprador exportador debe retener los impuestos respectivos y enterarlos a la SAT, o en el caso del IVA '],
            ['id' => 6, 'nombre' => 'Nota de Abono', 'codigo' => 'NABN', 'descripcion' => 'Documento emitido por los intermediarios de productos agropecuarios, artesanales o productos reciclados, destinados a la exportación, para efectuar compras a personas no registradas ante la SAT como proveedores de esos productos.2 También podrá utilizarse con previa autorización de la SAT para rebaja de inventarios, cuando el plazo para emitir la nota de crédito o la nota de débito haya transcurrido, por cualquier razón. Base legal: Decreto 27-92, Ley del IVA, artículo 52 “A”; Acuerdo Gubernativ'],
            ['id' => 7, 'nombre' => 'Recibo por donanción', 'codigo' => 'RDON', 'descripcion' => 'Documento que deben emitir las entidades no estatales para acreditar la recepción de donaciones. Base legal: Decreto 27-92, Ley del IVA artículo 7 numeral 9; Decreto 22003, Ley de Organizaciones No Gubernamentales para el Desarrollo artículo 15; Decreto 10-2012 Ley de Actualización Tributaria Libro I ISR, artículo 21 numeral 22; Acuerdo Gubernativo 13-2013, Reglamento del Libro I ISR, de la Ley Actualización Tributaria artículo 19. '],
            ['id' => 8, 'nombre' => 'Recibo', 'codigo' => 'RECI', 'descripcion' => 'Documento que emiten las asociaciones, fundaciones e instituciones educativas, de asistencia o de servicio social y las religiosas, y otras, por los servicios exentos que prestan. Base legal: Decreto 27-92 Ley del IVA art. 7 numeral 13.'],
            ['id' => 9, 'nombre' => 'Nota de Débito', 'codigo' => 'NDEB', 'descripcion' => 'Documento utilizado para aumentos del precio o recargos sobre operaciones ya facturadas. Base legal: Decreto 27-92, Ley del IVA, art. 29, literal c. '],
            ['id' => 10, 'nombre' => 'Nota de Crédito', 'codigo' => 'NCRE', 'descripcion' => 'Documento utilizado para devoluciones, anulaciones o descuentos sobre operaciones ya facturadas. Base legal: Decreto 27-92, Ley del IVA, art. 29, literal d. '],
            ['id' => 11, 'nombre' => 'Factura Contribuyente Agropecuario', 'codigo' => 'FACA', 'descripcion' => 'Documento que emite un contribuyente afiliado al Régimen Especial de Contribuyente Agropecuario.  Base legal: Decreto 27-92, Ley del IVA, artículo 54 “A”. '],
            ['id' => 12, 'nombre' => 'Factura Cambiaria Contribuyente Agropecuario', 'codigo' => 'FCCA', 'descripcion' => 'Documento que emite un vendedor de mercaderías afiliado al Régimen Especial de Contribuyente Agropecuario. El comprador lo devuelve debidamente aceptado, quedando obligado a pagar a su vencimiento la suma pactada. Es un título de crédito a favor del vendedor. Base legal: a) Decreto 2-70, Código de Comercio, artículo 591; b) Decreto 47-2008, Ley para el Reconocimiento de las Comunicaciones y Firmas Electrónicas, artículos 2 “Comercio Electrónico”, 7 y 9. '],
            ['id' => 13, 'nombre' => 'Factura Pequeño Contribuyente Régimen Electró', 'codigo' => 'FAPE', 'descripcion' => 'Documento que emite un contribuyente afiliado al Régimen Electrónico de Pequeño Contribuyente.  Base legal: Decreto 27-92, Ley del IVA, artículo 54 “E”.'],
            ['id' => 14, 'nombre' => 'Factura Cambiaria Pequeño Contribuyente Régim', 'codigo' => 'FCPE', 'descripcion' => 'Documento que emite un vendedor de mercaderías afiliado al Régimen Electrónico de Pequeño Contribuyente. El comprador lo devuelve debidamente aceptado, quedando obligado a pagar a su vencimiento la suma pactada. Es un título de crédito a favor del vendedor. Base legal: a) Decreto 2-70, Código de Comercio, artículo 591; b) Decreto 47-2008, Ley para el Reconocimiento de las Comunicaciones y Firmas Electrónicas, artículos 2 “Comercio Electrónico”, 7 y 9.'],
            ['id' => 15, 'nombre' => 'Factura Contribuyente Agropecuario Régimen El', 'codigo' => 'FAAE', 'descripcion' => 'Documento que emite un contribuyente afiliado al Régimen Electrónico Especial de Contribuyente Agropecuario.  Base legal: Decreto 27-92, Ley del IVA, artículo 54 “E”. '],
            ['id' => 16, 'nombre' => 'Factura Cambiaria Contribuyente Agropecuario ', 'codigo' => 'FCAE', 'descripcion' => 'Documento que emite un vendedor de mercaderías afiliado al Régimen Electrónico Especial de Contribuyente Agropecuario. El comprador lo devuelve debidamente aceptado, quedando obligado a pagar a su vencimiento la suma pactada. Es un título de crédito a favor del vendedor. Base legal: a) Decreto 2-70, Código de Comercio, artículo 591; b) Decreto 47-2008, Ley para el Reconocimiento de las Comunicaciones y Firmas Electrónicas, artículos 2 “Comercio Electrónico”, 7 y 9. '],
            ['id' => 17, 'nombre' => 'Constancia de Exención de IVA', 'codigo' => 'CIVA', 'descripcion' => 'Documento que emite un contribuyente que tenga registrado como mínimo un establecimiento como “EXENTO CONSTITUCIONAL” en el apartado “Clasificación por establecimiento”, esto para soportar que no será efectivo el pago del Impuesto Al Valor Agregado por la adquisición de bienes y/o prestación de servicios. Base Legal:   a) Decreto 27-92 Ley del Impuesto al Valor Agregado Artículo 9; b) Acuerdo Gubernativo No. 5-2013 Reglamento de la Ley del Impuesto al Valor Agregado Artículo 13 y 14. Documento que emite la Zona Libre de Industria y Comercio Santo Tomas de Castilla por las compras que realiza. Base Legal:   Decreto 22-73 Ley Organica de la "Zona Libre de Industria y Comercio Santo Tomas de Castilla", Artículo 31. '],
            ['id' => 18, 'nombre' => 'Constancias de Adquisición de Insumos y Servicios', 'codigo' => 'CAIS', 'descripcion' => 'Documentos que están obligados a emitir los contribuyentes con clasificación de “Maquila” cuando realicen compras de bienes o servicios a proveedores locales para ser incorporados directamente en el proceso de producción del bien que será destinado a la exportación o reexportación, las cuales no están afectas al pago de IVA.  Base legal: a) Decreto 29-89, Ley de fomento y desarrollo de la actividad exportadora y de maquila, artículo 36 bis; b) Acuerdo Gubernativo 53389 Reglamento de la Ley de fomento y desarrollo de la actividad exportadora y de maquila, artículo 30 "B". '],
            ['id' => 19, 'nombre' => 'Nota de Envío', 'codigo' => 'NEV', 'descripcion' => 'Documento que respalda el traslado de mercancías de un lugar a otro, la emisión de este tipo de documento no sustituye la obligación de la emisión del Documento Tributario Electrónico.'],
            ['id' => 20, 'nombre' => 'Recibo de anticipos', 'codigo' => 'RANT', 'descripcion' => 'Documento que respalda los pagos conocidos como anticipos en operaciones comerciales, este tipo de documento no sustituye la obligación de la emisión del Documento Tributario Electrónico.'],
        ];

        // DB::table('tipos_dte')->insert($tiposDte);
        TipoDte::insert($tiposDte);
   
    }
}
